name: Flutter CI

on:
  push:
    branches:
      - ver3  # 브랜치 이름을 ver3로 변경

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Flutter 설치
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 의존성 설치
      - run: flutter pub get

      # 환경 변수를 사용하여 빌드
      - run: flutter build apk --release --dart-define=API_URL=${{ secrets.API_URL }} --dart-define=GOOGLE_MAP_API_KEY=${{ secrets.GOOGLE_MAP_API_KEY }} --dart-define=NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}

      # iOS 빌드 (macOS 환경에서만 가능)
      - run: flutter build ios --release --dart-define=API_URL=${{ secrets.API_URL }} --dart-define=GOOGLE_MAP_API_KEY=${{ secrets.GOOGLE_MAP_API_KEY }} --dart-define=NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}
        if: runner.os == 'macOS'
