name: Flutter CI

on:
  push:
    branches:
      - main  # 또는 배포하려는 브랜치 이름

jobs:
  testing:
    runs-on: ubuntu-latest  # iOS 빌드를 원하면 'macos-latest'로 변경

    steps:
      - uses: actions/checkout@v2

      # Flutter 설치
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Dart SDK 버전 3.x.x에 맞는 최신 Flutter 버전

      # 의존성 설치
      - name: Install dependencies
        run: flutter pub get

      # 안드로이드 빌드 (Ubuntu에서 사용 가능)
      - name: Build Android APK
        run: flutter build apk --release --dart-define=API_URL=${{ secrets.API_URL }} --dart-define=GOOGLE_MAP_API_KEY=${{ secrets.GOOGLE_MAP_API_KEY }} --dart-define=NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}