name: Build and Distribute to TestFlight

on:
  push:
    branches:
      - ver3  # 또는 배포하려는 브랜치 이름

jobs:
  testflight:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 토큰 설정
      - name: Use GitHub Token
        run: echo "${{ secrets.GIT_TOKEN }}"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ipa --release --dart-define=API_URL=${{ secrets.API_URL }} --dart-define=GOOGLE_MAP_API_KEY=${{ secrets.GOOGLE_MAP_API_KEY }} --dart-define=NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app --type ios --file build/ios/ipa/*.ipa --apiKey ${{ secrets.APP_STORE_CONNECT_API_KEY }} --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }} --keyID ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
